### PR TITLE
7.2.6 EE Server release.

### PR DESCRIPTION
**Pull request by mhocouchbase**
7.2.6 EE Server release.

-Ming

### CODE REVIEW

**Comment by ceejatec** [comment]
We decided these changes weren't necessarily/desirable anymore, right? Same for CBL-C?

**Comment by mhocouchbase** [comment]
oh.  even for server 7.2.x?  https://confluence.issues.couchbase.com/wiki/spaces/CR/pages/2405402227/Couchbase+Server+Release+Process mentioned, this is needed for 7.2.x

**Comment by ceejatec** [comment]
Hmm... I guess we hadn't completely decided. But for what it's worth, it appears that 7.2.5 isn't in the "old" repos either, and I don't think anyone's complained. So...

**Comment by mhocouchbase** [comment]
okay.  I will go ahead w/o running the old job then.

**Pull request closed without merging**
